# Generated by Django 3.0.3 on 2020-03-11 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_room', models.IntegerField(db_index=True, unique=True, verbose_name='id')),
                ('name_room', models.CharField(max_length=100, verbose_name='Название помещения')),
                ('price_room', models.PositiveSmallIntegerField(verbose_name='Цена')),
                ('about_room', models.TextField(verbose_name='Информация')),
            ],
            options={
                'verbose_name': 'Помещение',
                'verbose_name_plural': 'Помещения',
            },
        ),
    ]
