# Generated by Django 3.0.3 on 2020-03-11 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='id_room',
        ),
        migrations.AlterField(
            model_name='room',
            name='name_room',
            field=models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Название помещения'),
        ),
    ]
