# Generated by Django 3.0.3 on 2020-03-14 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200311_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='image_room',
            field=models.ImageField(default='static/main/default.jpg', upload_to='', verbose_name='изображение'),
        ),
    ]
