# Generated by Django 3.0.3 on 2020-03-14 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_room_image_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='image_room',
            field=models.ImageField(default='static/main/default.png', upload_to='', verbose_name='изображение'),
        ),
    ]
