# Generated by Django 3.0.3 on 2020-03-14 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20200314_1125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='image_room',
        ),
    ]
